[package]
name = "cbor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
half = "1"
bstr = { version = "0.2", optional = true }
serde = { version = "1", optional = true }

[features]
no_std = []
serde1 = [ "serde" ]

[dev-dependencies]
anyhow = "1"
data-encoding = "2"
