[package]
name = "hongg-fuzz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
honggfuzz = "0.5"
serde = "1"
cbor4ii = { path = "..", features = [ "serde-value" ] }
